// Defender XDR Advanced Hunting schemas — transcribed from Microsoft Learn table reference pages (fetched 2026-09-29)
const INIT = "InitiatingProcessSHA1:string, InitiatingProcessSHA256:string, InitiatingProcessMD5:string, InitiatingProcessFileName:string, InitiatingProcessFileSize:long, InitiatingProcessVersionInfoCompanyName:string, InitiatingProcessVersionInfoProductName:string, InitiatingProcessVersionInfoProductVersion:string, InitiatingProcessVersionInfoInternalFileName:string, InitiatingProcessVersionInfoOriginalFileName:string, InitiatingProcessVersionInfoFileDescription:string, InitiatingProcessId:long, InitiatingProcessCommandLine:string, InitiatingProcessCreationTime:datetime, InitiatingProcessFolderPath:string, InitiatingProcessParentId:long, InitiatingProcessParentFileName:string, InitiatingProcessParentCreationTime:datetime, InitiatingProcessAccountDomain:string, InitiatingProcessAccountName:string, InitiatingProcessAccountSid:string, InitiatingProcessAccountUpn:string, InitiatingProcessAccountObjectId:string, InitiatingProcessIntegrityLevel:string, InitiatingProcessTokenElevation:string, InitiatingProcessSessionId:long, IsInitiatingProcessRemoteSession:bool, InitiatingProcessRemoteSessionDeviceName:string, InitiatingProcessRemoteSessionIP:string, InitiatingProcessUniqueId:string, ReportId:long, AppGuardContainerId:string, AdditionalFields:string";

const SIGNIN = "Timestamp:datetime, Application:string, ApplicationId:string, LogonType:string, EndpointCall:string, ErrorCode:int, CorrelationId:string, SessionId:string, AccountDisplayName:string, AccountObjectId:string, AccountUpn:string, IsExternalUser:int, IsGuestUser:bool, AlternateSignInName:string, LastPasswordChangeTimestamp:datetime, ResourceDisplayName:string, ResourceId:string, ResourceTenantId:string, DeviceName:string, OSPlatform:string, DeviceTrustType:string, IsManaged:int, IsCompliant:int, AuthenticationProcessingDetails:string, AuthenticationRequirement:string, RiskLevelAggregated:int, RiskState:int, UserAgent:string, ClientAppUsed:string, Browser:string, ConditionalAccessPolicies:string, ConditionalAccessStatus:int, IPAddress:string, Country:string, State:string, City:string, Latitude:string, Longitude:string, NetworkLocationDetails:string, RequestId:string, ReportId:string, EntraIdDeviceId:string";

module.exports = {
  EmailEvents: "Timestamp:datetime, NetworkMessageId:string, InternetMessageId:string, SenderMailFromAddress:string, SenderFromAddress:string, SenderDisplayName:string, SenderObjectId:string, SenderMailFromDomain:string, SenderFromDomain:string, SenderIPv4:string, SenderIPv6:string, RecipientEmailAddress:string, RecipientObjectId:string, Subject:string, EmailClusterId:long, EmailDirection:string, DeliveryAction:string, DeliveryLocation:string, ThreatTypes:string, ThreatNames:string, DetectionMethods:string, ConfidenceLevel:string, BulkComplaintLevel:int, EmailAction:string, EmailActionPolicy:string, EmailActionPolicyGuid:string, AuthenticationDetails:string, AttachmentCount:int, UrlCount:int, EmailLanguage:string, Connectors:string, OrgLevelAction:string, OrgLevelPolicy:string, UserLevelAction:string, UserLevelPolicy:string, ReportId:string, AdditionalFields:string, LatestDeliveryLocation:string, LatestDeliveryAction:string, OriginalThreatTypes:string, OriginalDetectionMethods:string, OriginalConfidenceLevel:string, DistributionList:string, ExchangeTransportRule:string, ForwardingInformation:string, Context:string, To:string, Cc:string, ThreatClassification:string, RecipientDomain:string, EmailSize:long, IsFirstContact:int, Topics:string",
  EmailUrlInfo: "Timestamp:datetime, NetworkMessageId:string, Url:string, UrlDomain:string, UrlLocation:string, UrlChainId:string, UrlChainPosition:int, ReportId:string",
  EmailAttachmentInfo: "Timestamp:datetime, NetworkMessageId:string, SenderFromAddress:string, SenderDisplayName:string, SenderObjectId:string, RecipientEmailAddress:string, RecipientObjectId:string, FileName:string, FileType:string, FileExtension:string, SHA256:string, FileSize:long, ThreatTypes:string, ThreatNames:string, DetectionMethods:string, ReportId:string, AdditionalFields:string",
  EmailPostDeliveryEvents: "Timestamp:datetime, NetworkMessageId:string, InternetMessageId:string, Action:string, ActionType:string, ActionTrigger:string, ActionResult:string, RecipientEmailAddress:string, DeliveryLocation:string, ThreatTypes:string, DetectionMethods:string, ReportId:string, SenderFromAddress:string, EmailDirection:string, SourceLocation:string",
  UrlClickEvents: "Timestamp:datetime, Url:string, ActionType:string, AccountUpn:string, Workload:string, NetworkMessageId:string, ThreatTypes:string, DetectionMethods:string, IPAddress:string, IsClickedThrough:bool, UrlChain:string, ReportId:string, AppName:string, AppVersion:string, SourceId:string",
  CloudAppEvents: "Timestamp:datetime, ActionType:string, Application:string, ApplicationId:int, AppInstanceId:int, AccountObjectId:string, AccountId:string, AccountDisplayName:string, IsAdminOperation:bool, DeviceType:string, OSPlatform:string, IPAddress:string, IsAnonymousProxy:bool, CountryCode:string, City:string, Isp:string, UserAgent:string, ActivityType:string, ActivityObjects:dynamic, ObjectName:string, ObjectType:string, ObjectId:string, ReportId:string, AccountType:string, IsExternalUser:bool, IsImpersonated:bool, IPTags:dynamic, IPCategory:string, UserAgentTags:dynamic, RawEventData:dynamic, AdditionalFields:dynamic, LastSeenForUser:dynamic, UncommonForUser:dynamic, AuditSource:string, SessionData:dynamic, OAuthAppId:string",
  DeviceProcessEvents: "Timestamp:datetime, DeviceId:string, DeviceName:string, ActionType:string, FileName:string, FolderPath:string, SHA1:string, SHA256:string, MD5:string, FileSize:long, ProcessVersionInfoCompanyName:string, ProcessVersionInfoProductName:string, ProcessVersionInfoProductVersion:string, ProcessVersionInfoInternalFileName:string, ProcessVersionInfoOriginalFileName:string, ProcessVersionInfoFileDescription:string, ProcessId:long, ProcessCommandLine:string, ProcessIntegrityLevel:string, ProcessTokenElevation:string, ProcessCreationTime:datetime, AccountDomain:string, AccountName:string, AccountSid:string, AccountUpn:string, AccountObjectId:string, LogonId:long, InitiatingProcessLogonId:long, InitiatingProcessSignerType:string, InitiatingProcessSignatureStatus:string, CreatedProcessSessionId:long, IsProcessRemoteSession:bool, ProcessRemoteSessionDeviceName:string, ProcessRemoteSessionIP:string, ProcessUniqueId:string, " + INIT,
  DeviceNetworkEvents: "Timestamp:datetime, DeviceId:string, DeviceName:string, ActionType:string, RemoteIP:string, RemotePort:int, RemoteUrl:string, LocalIP:string, LocalPort:int, Protocol:string, LocalIPType:string, RemoteIPType:string, " + INIT,
  DeviceFileEvents: "Timestamp:datetime, DeviceId:string, DeviceName:string, ActionType:string, FileName:string, FolderPath:string, SHA1:string, SHA256:string, MD5:string, FileOriginUrl:string, FileOriginReferrerUrl:string, FileOriginIP:string, PreviousFolderPath:string, PreviousFileName:string, FileSize:long, RequestProtocol:string, RequestSourceIP:string, RequestSourcePort:int, RequestAccountName:string, RequestAccountDomain:string, RequestAccountSid:string, ShareName:string, SensitivityLabel:string, SensitivitySubLabel:string, IsAzureInfoProtectionApplied:bool, " + INIT,
  DeviceLogonEvents: "Timestamp:datetime, DeviceId:string, DeviceName:string, ActionType:string, LogonType:string, AccountDomain:string, AccountName:string, AccountSid:string, Protocol:string, FailureReason:string, IsLocalAdmin:bool, LogonId:long, RemoteDeviceName:string, RemoteIP:string, RemoteIPType:string, RemotePort:int, " + INIT,
  DeviceEvents: "Timestamp:datetime, DeviceId:string, DeviceName:string, ActionType:string, FileName:string, FolderPath:string, SHA1:string, SHA256:string, MD5:string, FileSize:long, AccountDomain:string, AccountName:string, AccountSid:string, RemoteUrl:string, RemoteDeviceName:string, ProcessId:long, ProcessCommandLine:string, ProcessCreationTime:datetime, ProcessTokenElevation:string, LogonId:long, RegistryKey:string, RegistryValueName:string, RegistryValueData:string, RemoteIP:string, RemotePort:int, LocalIP:string, LocalPort:int, FileOriginUrl:string, FileOriginIP:string, InitiatingProcessLogonId:long, CreatedProcessSessionId:long, IsProcessRemoteSession:bool, ProcessRemoteSessionDeviceName:string, ProcessRemoteSessionIP:string, " + INIT,
  DeviceRegistryEvents: "Timestamp:datetime, DeviceId:string, DeviceName:string, ActionType:string, RegistryKey:string, RegistryValueType:string, RegistryValueName:string, RegistryValueData:string, PreviousRegistryKey:string, PreviousRegistryValueName:string, PreviousRegistryValueData:string, " + INIT.replace(", AdditionalFields:string", ""),
  IdentityLogonEvents: "Timestamp:datetime, ActionType:string, Application:string, LogonType:string, Protocol:string, FailureReason:string, AccountName:string, AccountDomain:string, AccountUpn:string, AccountSid:string, AccountObjectId:string, AccountDisplayName:string, DeviceName:string, DeviceType:string, OSPlatform:string, IPAddress:string, Port:int, DestinationDeviceName:string, DestinationIPAddress:string, DestinationPort:int, TargetDeviceName:string, TargetAccountDisplayName:string, Location:string, Isp:string, ReportId:string, AdditionalFields:dynamic",
  IdentityDirectoryEvents: "Timestamp:datetime, ActionType:string, Application:string, TargetAccountUpn:string, TargetAccountDisplayName:string, TargetDeviceName:string, DestinationDeviceName:string, DestinationIPAddress:string, DestinationPort:int, Protocol:string, AccountName:string, AccountDomain:string, AccountUpn:string, AccountSid:string, AccountObjectId:string, AccountDisplayName:string, DeviceName:string, IPAddress:string, Port:int, Location:string, ISP:string, ReportId:string, AdditionalFields:dynamic",
  IdentityQueryEvents: "Timestamp:datetime, ActionType:string, Application:string, QueryType:string, QueryTarget:string, Query:string, Protocol:string, AccountName:string, AccountDomain:string, AccountUpn:string, AccountSid:string, AccountObjectId:string, AccountDisplayName:string, DeviceName:string, IPAddress:string, Port:int, DestinationDeviceName:string, DestinationIPAddress:string, DestinationPort:int, TargetDeviceName:string, TargetAccountUpn:string, TargetAccountDisplayName:string, Location:string, ReportId:string, AdditionalFields:dynamic",
  AADSignInEventsBeta: SIGNIN + ", AadDeviceId:string, TokenIssuerType:int, RiskDetails:int",
  EntraIdSignInEvents: SIGNIN + ", TokenIssuerType:string, RiskLevelDuringSignIn:int, RiskEventTypes:string, GatewayJA4:string, TenantId:string, UniqueTokenId:string, IsSignInThroughGlobalSecureAccess:bool",
  AlertInfo: "Timestamp:datetime, AlertId:string, Title:string, Category:string, Severity:string, ServiceSource:string, DetectionSource:string, AttackTechniques:string",
  AlertEvidence: "Timestamp:datetime, AlertId:string, Title:string, Categories:string, AttackTechniques:string, ServiceSource:string, DetectionSource:string, EntityType:string, EvidenceRole:string, EvidenceDirection:string, FileName:string, FolderPath:string, SHA1:string, SHA256:string, FileSize:long, ThreatFamily:string, RemoteIP:string, RemoteUrl:string, AccountName:string, AccountDomain:string, AccountSid:string, AccountObjectId:string, AccountUpn:string, DeviceId:string, DeviceName:string, LocalIP:string, NetworkMessageId:string, EmailSubject:string, Application:string, ApplicationId:int, OAuthApplicationId:string, ProcessCommandLine:string, RegistryKey:string, RegistryValueName:string, RegistryValueData:string, AdditionalFields:string, Severity:string, CloudResource:string, CloudPlatform:string, ResourceType:string, ResourceID:string, SubscriptionId:string",
};
